apiVersion: apps/v1
kind: Deployment
metadata:
  name: confirm
  labels:
    app: confirm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confirm
  template:
    metadata:
      labels:
        app: confirm
    spec:
      containers:
        - name: confirm
          image: 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/team-e-confirm:latest # ECR image URI
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
